sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t benkennady/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true benkennady/docker-react npm run test